name: ilet
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  buttons_tabbar: ^1.3.8
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  get: ^4.6.5
  google_fonts: ^5.1.0
  pinput: ^3.0.1
  multi_select_flutter: ^4.1.3
  multi_dropdown: ^2.1.4
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.23
  toggle_switch: ^2.1.0
  intl: ^0.19.0
  dotted_border: ^2.1.0
  syncfusion_flutter_calendar: ^20.2.43
  timelines: ^0.1.0
  roundcheckbox: ^2.0.5
  contained_tab_bar_view: ^0.8.0
  stylish_bottom_bar: ^1.1.0
  convex_bottom_bar: ^3.2.0
  flutter_card_swiper: ^7.0.0
  simple_circular_progress_bar: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  device_preview: ^1.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/

flutter_assets:
  assets_path: assets/images/
  output_path: lib/constants/
  filename: app_images.dart
  field_prefix: ""



