// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRPHQyoEHsLbdVtzGDS7NeEEQIPN1x8x8',
    appId: '1:1015013291784:web:13a90ce5ecbff16e17debd',
    messagingSenderId: '1015013291784',
    projectId: 'bunetwork-64189',
    authDomain: 'bunetwork-64189.firebaseapp.com',
    storageBucket: 'bunetwork-64189.appspot.com',
    measurementId: 'G-QHCPWLYLPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc0tH0BxHSMK1FWZwk2EytNUsQTDknpKc',
    appId: '1:1015013291784:android:e2de130041c24f2917debd',
    messagingSenderId: '1015013291784',
    projectId: 'bunetwork-64189',
    storageBucket: 'bunetwork-64189.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwTKqIuCht63OSk0W5dKEAYUr7Lcnhdd8',
    appId: '1:1015013291784:ios:2d1d344f4ff8346817debd',
    messagingSenderId: '1015013291784',
    projectId: 'bunetwork-64189',
    storageBucket: 'bunetwork-64189.appspot.com',
    iosBundleId: 'com.example.ilet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwTKqIuCht63OSk0W5dKEAYUr7Lcnhdd8',
    appId: '1:1015013291784:ios:2d1d344f4ff8346817debd',
    messagingSenderId: '1015013291784',
    projectId: 'bunetwork-64189',
    storageBucket: 'bunetwork-64189.appspot.com',
    iosBundleId: 'com.example.ilet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRPHQyoEHsLbdVtzGDS7NeEEQIPN1x8x8',
    appId: '1:1015013291784:web:9a8f0c455f8445e017debd',
    messagingSenderId: '1015013291784',
    projectId: 'bunetwork-64189',
    authDomain: 'bunetwork-64189.firebaseapp.com',
    storageBucket: 'bunetwork-64189.appspot.com',
    measurementId: 'G-W1Q2FM6VM1',
  );
}
